[package]
name = "node-bbs-signatures"
description = "A node wrapper for bbs-signatures"
build = "build.rs"
edition = "2018"
version = "0.1.0"

[lib]
name = "node_bbs_signatures"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.4.0"

[dependencies]
bbs = { version = "0.1.0", git = "https://github.com/mikelodder7/ursa", rev = "54778517ebdb6aaba0180b341ec2b60486b9d5d7" }
neon = "0.4.0"